# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "szufbafdhfwqclyixdpd"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
# Port to use for the local database URL.
port = 54322

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.agent-response]
verify_jwt = true

[functions.delete-secret]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.process-workflow-stage]
verify_jwt = true