project_id = "szufbafdhfwqclyixdpd"
[build]
command = ""

[deploy]
allowed_imports = ["https://deno.land/std@0.168.0/http/server.ts", "https://esm.sh/@langchain/openai@0.0.14", "https://esm.sh/@langchain/core@0.1.63/prompts"]